### ISSUE TITLE
EPG - No information displays in guide

### ISSUE THREAD

**Issue by Leetxjd** [kodi-pvr/pvr.mediaportal.tvserver#153] opened 2021-11-24 05:40 UTC
Since Matrix - the EPG displays “no information” even though addon shows EPG data is updating.  Scheduled recordings do appear in the guide.

This occurs on latest AndroidTV.  Devices are a Sony Tv (running AndroidTV ) and a Nvidia Shield TV.

**Comment by phunkyfish** [comment] 2021-11-24 07:35
@AlwinEsch do you still have a media portal setup so we can check this?

**Comment by Leetxjd** [comment] 2021-11-24 16:05
Just another quick note on this - I can roll back to Leia and the EPG works fine.  If I permit the upgrade to Matrix (or load Nexus) the “Leia” data is displayed, but the EPG will not display data “obtained” or “loaded” under Matrix or Nexus.  The addon does indicate it is obtaining the data on startup.  It just never appears in the guide.

**Comment by phunkyfish** [comment] 2021-11-24 19:07
There were a number of changes to the PVR API. Specially with this addon the tcp connectivity was updated and the cause of this bug could be there.

**Comment by Leetxjd** [comment] 2021-11-25 04:55
Let me know if there is anything I can do to help.  I turned on the logging for the pvr addon on both the shield and TV.  I'll look around for the logfiles.  Another user on the Kodi Mediaportal forum posted the following:

ERROR <general>: AddOnLog: pvr.mediaportal.tvserver: TVServerKodi error: [ERROR]: No TV channels found
ERROR <general>: GetChannels: Add-on 'MediaPortal TV-server (DESKTOP):127.0.0.1:9596' returned an error: server error
ERROR <general>: PVR::CPVRClients::GetChannels: PVR client 'MediaPortal TV-server (DESKTOP):127.0.0.1:9596' returned an error: server error
ERROR <general>: GetChannelGroups: Add-on 'MediaPortal TV-server (DESKTOP):127.0.0.1:9596' returned an error: server error
ERROR <general>: PVR::CPVRClients::GetChannelGroups: PVR client 'MediaPortal TV-server (DESKTOP):127.0.0.1:9596' returned an error: server error
INFO <general>: PVR Manager: Started
ERROR <general>: AddOnLog: pvr.mediaportal.tvserver: Exception 'invalid stoi argument' during parse EPG data string.
INFO <general>: Skipped 14772 duplicate messages..

**Comment by phunkyfish** [comment] 2021-11-25 08:06
Could you generate a debug log? Instructions: https://kodi.wiki/view/Log_file/Easy

**Comment by Leetxjd** [comment] 2021-11-26 19:07
[kodi.log](https://github.com/kodi-pvr/pvr.mediaportal.tvserver/files/7610391/kodi.log)

I have created the log and it should be attached.

-LeeTXJD

**Comment by phunkyfish** [comment] 2021-11-27 09:19
Strange, no error on the channels like above in your log.

```

2021-11-26 12:43:43.489 T:9056    DEBUG <general>: Load: Loading all TV channel groups
2021-11-26 12:43:43.490 T:9056    DEBUG <general>: Get: Group 'All channels' loaded from PVR database
2021-11-26 12:43:43.491 T:9056    DEBUG <general>: Get: Group 'Broadcast' loaded from PVR database
2021-11-26 12:43:43.491 T:9056    DEBUG <general>: Get: Group 'Sat' loaded from PVR database
2021-11-26 12:43:43.492 T:9056    DEBUG <general>: Get: Group 'Movies' loaded from PVR database
2021-11-26 12:43:43.493 T:9056    DEBUG <general>: Get: Group 'Emby' loaded from PVR database
2021-11-26 12:43:43.493 T:9056    DEBUG <general>: Load: 5 TV groups fetched from the database
2021-11-26 12:43:43.501 T:8990    DEBUG <general>: ------ Window Init (DialogExtendedProgressBar.xml) ------
2021-11-26 12:43:43.501 T:9056    DEBUG <general>: Load: 382 channels loaded from the database for group 'All channels'
2021-11-26 12:43:43.502 T:9056    DEBUG <general>: AddOnLog: pvr.mediaportal.tvserver: GetChannels(tv) all channels
2021-11-26 12:43:43.742 T:8990    DEBUG <general>: ------ Window Deinit (DialogConfirm.xml) ------
2021-11-26 12:43:44.154 T:9056    DEBUG <general>: AddAndUpdateChannels: Updated TV channel '529 Starz Edge HD' from PVR client
2021-11-26 12:43:44.154 T:9056    DEBUG <general>: AddAndUpdateChannels: Updated TV channel '675 Fox Sports Southwest (Zone 4) HD' from PVR client
…

2021-11-26 12:43:46.013 T:9056    DEBUG <general>: AddAndUpdateChannels: Updated TV channel '703 NFL RedZone HD' in group 'Emby'
2021-11-26 12:43:46.014 T:9056    DEBUG <general>: PersistAll: Persisting all channel group changes
2021-11-26 12:43:46.014 T:9056    DEBUG <general>: Persist: Persisting channel group 'All channels' with 382 channels
2021-11-26 12:43:46.242 T:9056    DEBUG <general>: Load: 5 TV channel groups loaded
2021-11-26 12:43:46.242 T:9056    DEBUG <general>: Load: Loading all radio channel groups
2021-11-26 12:43:46.243 T:9056    DEBUG <general>: Load: 1 radio groups fetched from the database
2021-11-26 12:43:46.243 T:9056    DEBUG <general>: Load: 0 channels loaded from the database for group 'All channels'
```

Then I see all the epg data loaded in the log. Very strange. We may need to wait until @AlwinEsch has time to take a look.

**Comment by Leetxjd** [comment] 2021-11-27 16:03
That’s good.  Like I said, I am willing to help.

Way deep in the log - there are these entries (I guess they aren’t an issue?):

2021-11-26 12:43:58.148 T:9060    DEBUG <general>: UpdateFromScraper: Updating EPG for channel 'COZI' from client '1103839795'
2021-11-26 12:43:58.177 T:9060    DEBUG <general>: AddOnLog: pvr.mediaportal.tvserver: Found 284 EPG items for channel 565
                                                   
2021-11-26 12:43:58.178 T:9060    ERROR <general>: AddOnLog: pvr.mediaportal.tvserver: Exception 'stoi: no conversion' during parse EPG data string.
2021-11-26 12:43:58.297 T:9060    DEBUG <general>: Skipped 283 duplicate messages..
2021-11-26 12:43:58.297 T:9060    DEBUG <general>: UpdateFromScraper: Updating EPG for channel 'ION' from client '1103839795'
2021-11-26 12:43:58.343 T:9060    DEBUG <general>: AddOnLog: pvr.mediaportal.tvserver: Found 219 EPG items for channel 566
                                                   
2021-11-26 12:43:58.344 T:9060    ERROR <general>: AddOnLog: pvr.mediaportal.tvserver: Exception 'stoi: no conversion' during parse EPG data string.
2021-11-26 12:43:58.438 T:9060    DEBUG <general>: Skipped 218 duplicate messages..
2021-11-26 12:43:58.438 T:9060    DEBUG <general>: UpdateFromScraper: Updating EPG for channel '40-5 KXLKCD5 (KXLK-CD5)' from client '1103839795'
2021-11-26 12:43:58.466 T:9060    DEBUG <general>: AddOnLog: pvr.mediaportal.tvserver: Found 302 EPG items for channel 642
                                                   
2021-11-26 12:43:58.466 T:9060    ERROR <general>: AddOnLog: pvr.mediaportal.tvserver: Exception 'stoi: no conversion' during parse EPG data string.

**Comment by phunkyfish** [comment] 2021-11-27 17:55
I think the stoi no conversion error could be the cause

**Comment by phunkyfish** [comment] 2021-12-03 20:48
Can you try with these testbuilds?

https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.mediaportal.tvserver/detail/PR-155/1/artifacts

**Comment by Leetxjd** [comment] 2021-12-04 01:00
Yes, I'll do it this weekend for sure.

**Comment by Leetxjd** [comment] 2021-12-05 22:51
I can report that the testbuilds work on both the Sony TV and the Nvidia Shield.

Full guide data.  All other functionality seems to be present as well.

**Comment by mshoemaker** [comment] 2021-12-05 22:55
This is awesome news.  Now I just need a build for raspberry pi.

**Comment by Leetxjd** [comment] 2021-12-06 03:42
I'm sure the authors will accommodate and incorporate their changes into all versions.  Since I have never run Kodi and  Pi, I don't have insight.

**Comment by phunkyfish** [comment] 2021-12-06 09:45
> This is awesome news. Now I just need a build for raspberry pi.
> […](#)

Once this change is merged the next version for the different platforms will also incorporate it. 

If the platform ships the addons with kodi you would need to wait for the next release. If they have their own binary addon repo it will be much quicker.

**Comment by phunkyfish** [comment] 2021-12-07 08:30
Fix released for both Matrix and Nexus branches.

**Closed as completed by phunkyfish** 2021-12-07 08:30 UTC
